stages:
  - test
  - publish
  - release

.test: &test
  stage: test
  image: node:18-alpine
  cache:
    key: static
    paths:
      - .pnpm-store
  before_script:
    - npm i -g pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm i

lint:
  <<: *test
  only:
    - /^test(\/.*)?$/
    - /^release\/.+$/
  script:
    - pnpm lint

publish npm:
  stage: publish
  image: node:18-alpine
  cache:
    key: static
    paths:
      - .pnpm-store
  before_script:
    - npm i -g pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm i
    - export VERSION=$(node -p "require('./package.json').version")
    - echo "VERSION=$VERSION" >> variables.env
  rules:
    # Do not run this job for tags
    - if: $CI_COMMIT_REF_NAME != $CI_COMMIT_BRANCH || $CI_COMMIT_BRANCH == 'dev'
      when: never
    - when: always
  script:
    - pnpm publish
  artifacts:
    reports:
      dotenv: variables.env
    when: on_success

release prod:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    # Do not run this job for tags
    - if: $CI_COMMIT_REF_NAME != $CI_COMMIT_BRANCH || $CI_COMMIT_BRANCH == 'dev'
      when: never
    - when: on_success
  needs:
    - job: publish npm
      artifacts: true
  script:
    - echo "Release $VERSION"
    - |
      release-cli create --name "Release $VERSION" --tag-name v$VERSION \
        --description 'Created using the release-cli. $CI_COMMIT_TITLE' --ref $CI_COMMIT_SHA
