import { createApiService } from '@gertsai/api-core/moleculer';
import RLRMiddleware from '@gertsai/api-rlr';
import IORedis from 'ioredis';

import config from '../../project.config';
import { sseIngestAliasHandler } from './sse-ingest.handler';

// `package.json` is loaded at runtime and embedded into the response envelope
// by createApiService. Resolved relative to `process.cwd()` (set by `pnpm start`
// to the package directory) so the lookup works identically from `src/` (dev,
// ts-node-dev) and `dist/src/` (compiled, `node dist/src/index.js`) — earlier
// fixed-`require('../../package.json')` shifted by one level after compile.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pkg = require(`${process.cwd()}/package.json`) as Record<string, unknown>;

// =============================================================================
// Rate limiter (@gertsai/api-rlr) — pipeline pattern
//
// RLR sits as an Express-style middleware in moleculer-web's `settings.use`
// chain (BEFORE Moleculer routes). It's gated on REDIS_URL since the only
// shipped store is Redis-shaped. When disabled, the chain is empty and no
// throttling happens — useful for local single-process dev.
//
// See apps/pipeline/src/mol-services/api.service.ts for the production
// reference (per-route presets + tenant key extraction + IP fallback).
// =============================================================================

const rlrUseChain = config.RLR_ENABLED && config.REDIS_URL
  ? [
      RLRMiddleware({
        timeFrame: config.RLR_TIMEFRAME,
        limit: config.RLR_LIMIT,
        burst: config.RLR_BURST,
        // Cast to LimiterStrategy literal — env strings are validated at
        // import time but TS can't infer the union narrowing here.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        strategy: config.RLR_STRATEGY as any,
        prefix: config.RLR_PREFIX,
        store: () =>
          new IORedis(config.REDIS_URL, {
            maxRetriesPerRequest: 1,
            lazyConnect: true,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
          }) as any,
        bucketKeyResolver: (req: { headers: Record<string, string | string[] | undefined> }) => {
          // Pipeline pattern: tenant-scoped bucket if X-Tenant-ID present;
          // otherwise fall back to client IP. Real apps should call
          // `validateTenantIdFormat()` from @gertsai/api-core to prevent
          // Redis-injection via raw header values.
          const rawTenant = req.headers['x-tenant-id'] ?? req.headers['x-tenant'];
          const tenantId = Array.isArray(rawTenant) ? rawTenant[0] : rawTenant;
          if (tenantId && /^[a-zA-Z0-9_-]{1,64}$/.test(tenantId)) {
            return `tenant:${tenantId}`;
          }
          // Lightweight IP extractor for example purposes — pipeline uses
          // `extractClientIp` from @gertsai/api-core for proxy-aware headers.
          const xff = req.headers['x-forwarded-for'];
          const ip = Array.isArray(xff) ? xff[0] : xff;
          return `ip:${((ip ?? 'unknown').split(',')[0] ?? 'unknown').trim()}`;
        },
      }),
    ]
  : [];

/**
 * API Gateway service — exposes the registered Moleculer actions over HTTP.
 *
 * Route layout:
 *   - `/api/v1/*`   — REST endpoints generated by ApiController autoAliases.
 *   - `/openapi`    — placeholder for the OpenAPI document. Wire a real
 *                     generator (typia.json.schema + generateOpenAPISchema)
 *                     once the example grows.
 *
 * The API is intentionally permissive (CORS `*`, no auth) so the example
 * is friction-free to try locally. Tighten before any non-toy deployment.
 */
export function createDocumentsApiService() {
  return createApiService(
    {
      name: 'api',
      // OAuth mixin is not needed for the example; disabling it also frees
      // us from configuring an OAuth model.
      disableAuth: true,

      settings: {
        port: Number(process.env.WEB_SERVER_PORT ?? 3000),

        cors: {
          origin: '*',
          methods: ['GET', 'POST', 'OPTIONS'],
          allowedHeaders: ['Content-Type', 'Authorization', 'X-Tenant-ID', 'X-Request-ID'],
        },

        // -------------------------------------------------------------------
        // Express-style middleware chain. moleculer-web's built-in rate
        // limiter is disabled (rateLimit: null) so api-rlr is the only
        // throttling pass. See `rlrUseChain` above for gating.
        // -------------------------------------------------------------------
        rateLimit: null,
        use: rlrUseChain,

        routes: [
          {
            path: '/api/v1',
            // Auto-generate REST aliases from action `rest` strings.
            autoAliases: true,
            // Body parsing
            bodyParsers: {
              json: { strict: false, limit: '1MB' },
              urlencoded: { extended: true, limit: '1MB' },
            },
            // Allow access to all v1.* actions registered via ApiController.
            // Double-asterisk matches nested action names (v1.ingest.document
            // is "v1" + "ingest" + "document" — single-asterisk only matches
            // one segment). Pipeline uses the same `v1.<service>.**` shape.
            whitelist: ['v1.**'],
            // ApiController already wraps responses; no auth at the gateway.
            authentication: false,
            authorization: false,
          },
          {
            // Wave 9.0.1: route the broker-registered `v2.openapi.*` service
            // over HTTP via autoAliases. Replaces the static placeholder.
            // `createOpenApiService` (registered in src/index.ts) declares:
            //   - `v2.openapi.schema.aggregated` with rest: 'GET /schema.json'
            //   - `v2.openapi.schema.local`      with rest: 'GET /schema.local.json'
            // moleculer-web `autoAliases: true` picks up the rest field and
            // maps both into this `/openapi/*` route prefix.
            //
            // Full typia auto-derive (replacing the hand-curated
            // src/openapi/schema.ts literal) is deferred to Wave 9.0.2 —
            // it requires removing `: any` annotations from every action
            // export so typia can introspect their handler param/response
            // shapes (scope creep beyond Wave 9.0.1 maintenance).
            path: '/openapi',
            autoAliases: true,
            bodyParsers: {
              json: { strict: false, limit: '1MB' },
            },
            whitelist: ['v2.openapi.**'],
            authentication: false,
            authorization: false,
          },
          {
            // Wave 10.B (PRD-019 FR-002) — Server-Sent Events stream for
            // ingest pipeline lifecycle events. The alias handler is a
            // bare `(req, res)` function (not a Moleculer action) so we
            // can keep the connection open and write SSE frames directly.
            //
            //  - `use: []`  no rate-limiter on long-lived streams; the
            //               token bucket would close otherwise-healthy
            //               connections when their listener slot ages out.
            //  - `bodyParsers: false`   SSE is a GET with no body.
            //  - `authentication/authorization: false`   matches the
            //               permissive policy of the other example routes;
            //               tighten before any non-toy deployment.
            //
            // See `sse-ingest.handler.ts` for docId validation, idle
            // timeout, and cleanup semantics.
            path: '/api/stream',
            use: [],
            aliases: {
              'GET ingest': sseIngestAliasHandler,
            },
            authentication: false,
            authorization: false,
            bodyParsers: false,
          },
        ],
      },
    },
    pkg,
  );
}

export default createDocumentsApiService();
