import { createApiService } from '@gertsai/api-core';

// `package.json` is read at build-time and embedded into the response
// envelope by createApiService. We import it as JSON.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pkg = require('../../package.json') as Record<string, unknown>;

/**
 * API Gateway service — exposes the registered Moleculer actions over HTTP.
 *
 * Route layout:
 *   - `/api/v1/*`   — REST endpoints generated by ApiController autoAliases.
 *   - `/openapi`    — placeholder for the OpenAPI document. Wire a real
 *                     generator (typia.json.schema + generateOpenAPISchema)
 *                     once the example grows.
 *
 * The API is intentionally permissive (CORS `*`, no auth) so the example
 * is friction-free to try locally. Tighten before any non-toy deployment.
 */
export function createDocumentsApiService() {
  return createApiService(
    {
      name: 'api',
      // OAuth mixin is not needed for the example; disabling it also frees
      // us from configuring an OAuth model.
      disableAuth: true,

      settings: {
        port: Number(process.env.WEB_SERVER_PORT ?? 3000),

        cors: {
          origin: '*',
          methods: ['GET', 'POST', 'OPTIONS'],
          allowedHeaders: ['Content-Type', 'Authorization', 'X-Tenant-ID', 'X-Request-ID'],
        },

        // -------------------------------------------------------------------
        // Express-style middleware chain.
        //
        // TODO: add RLRMiddleware from @gertsai/api-rlr once extracted (Phase 2)
        //   .use(RLRMiddleware({ default: { rule: { type: 'gcra', limit: 60, period: 60 } } }))
        //
        // For now we keep the chain empty — moleculer-web's built-in
        // rate-limiting is also disabled to avoid double-throttling once
        // RLR lands.
        // -------------------------------------------------------------------
        rateLimit: null,
        use: [],

        routes: [
          {
            path: '/api/v1',
            // Auto-generate REST aliases from action `rest` strings.
            autoAliases: true,
            // Body parsing
            bodyParsers: {
              json: { strict: false, limit: '1MB' },
              urlencoded: { extended: true, limit: '1MB' },
            },
            // Allow access to all v1.* actions registered via ApiController.
            whitelist: ['v1.*'],
            // ApiController already wraps responses; no auth at the gateway.
            authentication: false,
            authorization: false,
          },
          {
            // Placeholder: serves a static OpenAPI shell. Replace once
            // typia.json.schema<OpenApiMapper<...>>() is wired in composition.
            path: '/openapi',
            aliases: {
              'GET /'(_req: unknown, res: { setHeader: (k: string, v: string) => void; end: (b: string) => void }) {
                res.setHeader('content-type', 'application/json');
                res.end(
                  JSON.stringify({
                    openapi: '3.1.0',
                    info: { title: 'm9s-example', version: '0.0.1' },
                    paths: {
                      '/api/v1/ingest': {
                        post: { summary: 'Ingest a document', responses: { 201: { description: 'Created' } } },
                      },
                      '/api/v1/search': {
                        post: { summary: 'Search documents', responses: { 200: { description: 'OK' } } },
                      },
                    },
                  }),
                );
              },
            },
          },
        ],
      },
    },
    pkg,
  );
}

export default createDocumentsApiService();
