import { createApiService } from '@gertsai/api-core/moleculer';
import RLRMiddleware from '@gertsai/api-rlr';
import IORedis from 'ioredis';

import config from '../../project.config';

// `package.json` is loaded at runtime and embedded into the response envelope
// by createApiService. Resolved relative to `process.cwd()` (set by `pnpm start`
// to the package directory) so the lookup works identically from `src/` (dev,
// ts-node-dev) and `dist/src/` (compiled, `node dist/src/index.js`) — earlier
// fixed-`require('../../package.json')` shifted by one level after compile.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pkg = require(`${process.cwd()}/package.json`) as Record<string, unknown>;

// =============================================================================
// Rate limiter (@gertsai/api-rlr) — pipeline pattern
//
// RLR sits as an Express-style middleware in moleculer-web's `settings.use`
// chain (BEFORE Moleculer routes). It's gated on REDIS_URL since the only
// shipped store is Redis-shaped. When disabled, the chain is empty and no
// throttling happens — useful for local single-process dev.
//
// See apps/pipeline/src/mol-services/api.service.ts for the production
// reference (per-route presets + tenant key extraction + IP fallback).
// =============================================================================

const rlrUseChain = config.RLR_ENABLED && config.REDIS_URL
  ? [
      RLRMiddleware({
        timeFrame: config.RLR_TIMEFRAME,
        limit: config.RLR_LIMIT,
        burst: config.RLR_BURST,
        // Cast to LimiterStrategy literal — env strings are validated at
        // import time but TS can't infer the union narrowing here.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        strategy: config.RLR_STRATEGY as any,
        prefix: config.RLR_PREFIX,
        store: () =>
          new IORedis(config.REDIS_URL, {
            maxRetriesPerRequest: 1,
            lazyConnect: true,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
          }) as any,
        bucketKeyResolver: (req: { headers: Record<string, string | string[] | undefined> }) => {
          // Pipeline pattern: tenant-scoped bucket if X-Tenant-ID present;
          // otherwise fall back to client IP. Real apps should call
          // `validateTenantIdFormat()` from @gertsai/api-core to prevent
          // Redis-injection via raw header values.
          const rawTenant = req.headers['x-tenant-id'] ?? req.headers['x-tenant'];
          const tenantId = Array.isArray(rawTenant) ? rawTenant[0] : rawTenant;
          if (tenantId && /^[a-zA-Z0-9_-]{1,64}$/.test(tenantId)) {
            return `tenant:${tenantId}`;
          }
          // Lightweight IP extractor for example purposes — pipeline uses
          // `extractClientIp` from @gertsai/api-core for proxy-aware headers.
          const xff = req.headers['x-forwarded-for'];
          const ip = Array.isArray(xff) ? xff[0] : xff;
          return `ip:${(ip ?? 'unknown').split(',')[0].trim()}`;
        },
      }),
    ]
  : [];

/**
 * API Gateway service — exposes the registered Moleculer actions over HTTP.
 *
 * Route layout:
 *   - `/api/v1/*`   — REST endpoints generated by ApiController autoAliases.
 *   - `/openapi`    — placeholder for the OpenAPI document. Wire a real
 *                     generator (typia.json.schema + generateOpenAPISchema)
 *                     once the example grows.
 *
 * The API is intentionally permissive (CORS `*`, no auth) so the example
 * is friction-free to try locally. Tighten before any non-toy deployment.
 */
export function createDocumentsApiService() {
  return createApiService(
    {
      name: 'api',
      // OAuth mixin is not needed for the example; disabling it also frees
      // us from configuring an OAuth model.
      disableAuth: true,

      settings: {
        port: Number(process.env.WEB_SERVER_PORT ?? 3000),

        cors: {
          origin: '*',
          methods: ['GET', 'POST', 'OPTIONS'],
          allowedHeaders: ['Content-Type', 'Authorization', 'X-Tenant-ID', 'X-Request-ID'],
        },

        // -------------------------------------------------------------------
        // Express-style middleware chain. moleculer-web's built-in rate
        // limiter is disabled (rateLimit: null) so api-rlr is the only
        // throttling pass. See `rlrUseChain` above for gating.
        // -------------------------------------------------------------------
        rateLimit: null,
        use: rlrUseChain,

        routes: [
          {
            path: '/api/v1',
            // Auto-generate REST aliases from action `rest` strings.
            autoAliases: true,
            // Body parsing
            bodyParsers: {
              json: { strict: false, limit: '1MB' },
              urlencoded: { extended: true, limit: '1MB' },
            },
            // Allow access to all v1.* actions registered via ApiController.
            // Double-asterisk matches nested action names (v1.ingest.document
            // is "v1" + "ingest" + "document" — single-asterisk only matches
            // one segment). Pipeline uses the same `v1.<service>.**` shape.
            whitelist: ['v1.**'],
            // ApiController already wraps responses; no auth at the gateway.
            authentication: false,
            authorization: false,
          },
          {
            // Placeholder: serves a static OpenAPI shell. Replace once
            // typia.json.schema<OpenApiMapper<...>>() is wired in (the
            // pipeline app does this via `@gerts/api-types`, which is not
            // yet extracted into this monorepo).
            path: '/openapi',
            aliases: {
              'GET /'(_req: unknown, res: { setHeader: (k: string, v: string) => void; end: (b: string) => void }) {
                res.setHeader('content-type', 'application/json');
                res.end(
                  JSON.stringify({
                    openapi: '3.1.0',
                    info: { title: 'm9s-example', version: '0.0.1' },
                    paths: {
                      '/api/v1/ingest/document': {
                        post: { summary: 'Ingest a document', responses: { 201: { description: 'Created' } } },
                      },
                      '/api/v1/search/query': {
                        post: { summary: 'Search documents', responses: { 200: { description: 'OK' } } },
                      },
                    },
                  }),
                );
              },
            },
          },
        ],
      },
    },
    pkg,
  );
}

export default createDocumentsApiService();
