import { z } from 'zod';
export declare const DocumentMetadataSchema: z.ZodObject<{
    file_path: z.ZodOptional<z.ZodString>;
    file_name: z.ZodOptional<z.ZodString>;
    file_type: z.ZodOptional<z.ZodString>;
    file_size: z.ZodOptional<z.ZodNumber>;
    Header_1: z.ZodOptional<z.ZodString>;
    Header_2: z.ZodOptional<z.ZodString>;
    Header_3: z.ZodOptional<z.ZodString>;
    section_path: z.ZodOptional<z.ZodString>;
    source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
    url: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    modified_at: z.ZodOptional<z.ZodString>;
    extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    file_path: z.ZodOptional<z.ZodString>;
    file_name: z.ZodOptional<z.ZodString>;
    file_type: z.ZodOptional<z.ZodString>;
    file_size: z.ZodOptional<z.ZodNumber>;
    Header_1: z.ZodOptional<z.ZodString>;
    Header_2: z.ZodOptional<z.ZodString>;
    Header_3: z.ZodOptional<z.ZodString>;
    section_path: z.ZodOptional<z.ZodString>;
    source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
    url: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    modified_at: z.ZodOptional<z.ZodString>;
    extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    file_path: z.ZodOptional<z.ZodString>;
    file_name: z.ZodOptional<z.ZodString>;
    file_type: z.ZodOptional<z.ZodString>;
    file_size: z.ZodOptional<z.ZodNumber>;
    Header_1: z.ZodOptional<z.ZodString>;
    Header_2: z.ZodOptional<z.ZodString>;
    Header_3: z.ZodOptional<z.ZodString>;
    section_path: z.ZodOptional<z.ZodString>;
    source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
    url: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    modified_at: z.ZodOptional<z.ZodString>;
    extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, z.ZodTypeAny, "passthrough">>;
export type DocumentMetadata = z.infer<typeof DocumentMetadataSchema>;
export declare const DocumentSchema: z.ZodObject<{
    id: z.ZodString;
    text: z.ZodString;
    metadata: z.ZodDefault<z.ZodObject<{
        file_path: z.ZodOptional<z.ZodString>;
        file_name: z.ZodOptional<z.ZodString>;
        file_type: z.ZodOptional<z.ZodString>;
        file_size: z.ZodOptional<z.ZodNumber>;
        Header_1: z.ZodOptional<z.ZodString>;
        Header_2: z.ZodOptional<z.ZodString>;
        Header_3: z.ZodOptional<z.ZodString>;
        section_path: z.ZodOptional<z.ZodString>;
        source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
        url: z.ZodOptional<z.ZodString>;
        created_at: z.ZodOptional<z.ZodString>;
        modified_at: z.ZodOptional<z.ZodString>;
        extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "passthrough", z.ZodTypeAny, z.objectOutputType<{
        file_path: z.ZodOptional<z.ZodString>;
        file_name: z.ZodOptional<z.ZodString>;
        file_type: z.ZodOptional<z.ZodString>;
        file_size: z.ZodOptional<z.ZodNumber>;
        Header_1: z.ZodOptional<z.ZodString>;
        Header_2: z.ZodOptional<z.ZodString>;
        Header_3: z.ZodOptional<z.ZodString>;
        section_path: z.ZodOptional<z.ZodString>;
        source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
        url: z.ZodOptional<z.ZodString>;
        created_at: z.ZodOptional<z.ZodString>;
        modified_at: z.ZodOptional<z.ZodString>;
        extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.ZodTypeAny, "passthrough">, z.objectInputType<{
        file_path: z.ZodOptional<z.ZodString>;
        file_name: z.ZodOptional<z.ZodString>;
        file_type: z.ZodOptional<z.ZodString>;
        file_size: z.ZodOptional<z.ZodNumber>;
        Header_1: z.ZodOptional<z.ZodString>;
        Header_2: z.ZodOptional<z.ZodString>;
        Header_3: z.ZodOptional<z.ZodString>;
        section_path: z.ZodOptional<z.ZodString>;
        source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
        url: z.ZodOptional<z.ZodString>;
        created_at: z.ZodOptional<z.ZodString>;
        modified_at: z.ZodOptional<z.ZodString>;
        extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.ZodTypeAny, "passthrough">>>;
    embedding: z.ZodOptional<z.ZodArray<z.ZodNumber, "many">>;
}, "strip", z.ZodTypeAny, {
    id: string;
    text: string;
    metadata: {
        file_path?: string | undefined;
        file_name?: string | undefined;
        file_type?: string | undefined;
        file_size?: number | undefined;
        Header_1?: string | undefined;
        Header_2?: string | undefined;
        Header_3?: string | undefined;
        section_path?: string | undefined;
        url?: string | undefined;
        source_type?: "stream" | "file" | "url" | "memory" | undefined;
        created_at?: string | undefined;
        modified_at?: string | undefined;
        extra?: Record<string, unknown> | undefined;
    } & {
        [k: string]: unknown;
    };
    embedding?: number[] | undefined;
}, {
    id: string;
    text: string;
    metadata?: z.objectInputType<{
        file_path: z.ZodOptional<z.ZodString>;
        file_name: z.ZodOptional<z.ZodString>;
        file_type: z.ZodOptional<z.ZodString>;
        file_size: z.ZodOptional<z.ZodNumber>;
        Header_1: z.ZodOptional<z.ZodString>;
        Header_2: z.ZodOptional<z.ZodString>;
        Header_3: z.ZodOptional<z.ZodString>;
        section_path: z.ZodOptional<z.ZodString>;
        source_type: z.ZodOptional<z.ZodEnum<["file", "url", "stream", "memory"]>>;
        url: z.ZodOptional<z.ZodString>;
        created_at: z.ZodOptional<z.ZodString>;
        modified_at: z.ZodOptional<z.ZodString>;
        extra: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.ZodTypeAny, "passthrough"> | undefined;
    embedding?: number[] | undefined;
}>;
export type Document = z.infer<typeof DocumentSchema>;
export declare function createDocument(text: string, metadata?: Partial<DocumentMetadata>): Document;
